### ISSUE TITLE
Float_sto returning INVALID_ARGUMENT for some valid inputs

### ISSUE THREAD

**Issue by technotip** [RichardAH/rippled-hooks#10]
## Issue Description

[float_sto](https://xrpl-hooks.readme.io/reference/float_sto) returns error code -7 which corresponds to INVALID_ARGUMENT, for some valid inputs.

## Steps to Reproduce

```C
{
   uint8_t amt_out[48];
   int64_t result =  float_sto(SBUF(amt_out), SBUF(currency), SBUF(hook_acc_id), float_set(0, 2), sfAmount); 

   trace_num(SBUF("Testcase5:"), result);
   ASSERT(result);
}
```

## Expected Result

It should serialise the given input and write it to the buffer memory represented by amt_out.

## Actual Result

It's returning error code -7, indicating INVALID_ARGUMENT.

**Comment by RichardAH** [comment]
This appears to be fixed. Please re-open if it isn't.
