### ISSUE TITLE
Emitted Transactions fee is too high

### ISSUE THREAD

**Issue by yxxyun** [RichardAH/rippled-hooks#17]
## Issue Description
Emitted Transactions fee is too high

## Steps to Reproduce

1. `node doubler.js saUC1cTtSLiD9hfGWmC4gqifX4ub2`
2. `node pay.js sn8NQoG6cwwhgyhMpNWDDfhppE1yZ 1 rNFokMEF3VEHLd5t8SKC1KNS9vhvtPgnvA`
3. when got the etmitted tx

    `./rippled tx A27866C93C2B0D3C573FC1A3B8CBA5E186BE4C41D5A2DCC44C3CD214546BED20`
     
    `{
   "result" : {
      "Account" : "rNFokMEF3VEHLd5t8SKC1KNS9vhvtPgnvA",
      "Amount" : "2000000",
      "Destination" : "rGMWrC2cStr8gHsH2QWtwfbUue5gGbWARL",
      "DestinationTag" : 0,
      "EmitDetails" : {
         "EmitBurden" : "0000000000000001",
         "EmitCallback" : "rNFokMEF3VEHLd5t8SKC1KNS9vhvtPgnvA",
         "EmitGeneration" : 2,
         "EmitNonce" : "39938C2A0F93238F44D2961E1A741A39E7D3EDC52E9DEC415A01A9BA403B9289",
         "EmitParentTxnID" : "18AE8BFFC65C6067FF07AAF43319C58CB7AF8A17D7B7EB89C56ED24CDBF43F06"
      },
      **"Fee" : "81468750",**
      "FirstLedgerSequence" : 1143886,
      "Flags" : 2147483648,
      "LastLedgerSequence" : 1143890,
      "Sequence" : 0,
      "SigningPubKey" : "000000000000000000000000000000000000000000000000000000000000000000",
      "SourceTag" : 0,
      "TransactionType" : "Payment",
      "date" : 675583570,
      "hash" : "A27866C93C2B0D3C573FC1A3B8CBA5E186BE4C41D5A2DCC44C3CD214546BED20",
      "inLedger" : 1143886,
      "ledger_index" : 1143886,
      "meta" : {......`

## Result
the fee is 81XRP, is too high.

## Environment
wss://hooks-testnet.xrpl-labs.com

**Comment by intelliot** [comment]
Discussion: https://github.com/XRPL-Labs/xrpld-hooks/discussions/16

**Comment by yxxyun** [comment]
https://hooks-testnet-explorer.xrpl-labs.com/tx/5D0AFFCF9EBDDB60B0BB4233FB4E78E6D910D95754B8EA57E563C66F0AEED5BA

**Comment by WietseWind** [comment]
> Migrated from Discussion:

### Discussed in https://github.com/XRPL-Labs/xrpld-hooks/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **yxxyun** May 28, 2021</sup>
Just test the doubler:
![20210528111909](https://user-images.githubusercontent.com/107192/119924646-94642700-bfa6-11eb-9ff6-cedb22e3c801.png)
</div>

**Comment by WietseWind** [comment]
@RichardAH

**Comment by SavindaSenevirathne** [comment]
A simple XRP transaction emission from hook cost around 81 XRP as of testing.

Sample code: [high_fee.zip](https://github.com/XRPL-Labs/xrpld-hooks/files/7716719/high_fee.zip)

### Running Instructions.
- Run the `run.js` file with following parameters.
  - Hook secret
  - Rippled server URL

```bash
node run.js sn6Eh5HPDsmsPG4RgnHCVFSgoo7FH ws://localhost:6005
```

**Note**:
- The script will compile the hook code and upload to the account with given secret.
- It will submit transactions in order to invoke transaction emission from hook.

**Comment by RichardAH** [comment]
I believe this was fixed quite a while ago, please re-open if still occurring. (Can't reproduce it now.)
