### ISSUE TITLE
Hook telemetry

### ISSUE THREAD

**Issue by shortthefomo** [RichardAH/rippled-hooks#24]
## Summary
Hook telemetry would provide a way to pull data out the hook for monitoring purposes. 

## Motivation

- Via this analytical info can be abstracted from the hook.
- Realtime debugging of the "contracts" then becomes possible. We can then add alerts when contracts fall into some states they should never have found them selves in. The list goes on...

## Solution

- Proposal is something similar to the account_tx method where by you can subscribe to the webhook and monitor the transactions. But in this case the proposal is to return debug eg. console.log() or some watered down version of that. 
- Possibly listening to this hook could require a signed tx its self so that not everyone in the world can listen but only the creators. (maybe im over thinking security)

## Paths Not Taken
Security issues... im not sure of all of them.

**Comment by WietseWind** [comment]
E.g. on a admin websocket. That's a great idea, subscribe to hook events for a specific account. @RichardAH
