### ISSUE TITLE
State objects not created if the reserve not enough. No error code return in state_set.

### ISSUE THREAD

**Issue by SavindaSenevirathne** [RichardAH/rippled-hooks#26]
## Issue Description
State objects are not created if the account reserve is not enough. `state_set` doesn't return any error code.

## Steps to Reproduce
Sample code: [state_reserve_not_creating.zip](https://github.com/XRPL-Labs/xrpld-hooks/files/7625966/state_reserve_not_creating.zip)
- Download and run the given sample code.
```bash
node run.js sn6Eh5HPDsmsPG4RgnHCVFSgoo7FH ws://localhost:6005
```
- It will compile and upload the hook to the given account and then will print the number of state objects before and after state creation.

## Expected Result
Transaction invoking the state creation should be rejected by the hook since state creation is not finished properly.

## Actual Result
Transaction invoking the state creation is accepted by the hook since no error is returned from `set_state`. But no state object is created.

## Environment
Ubuntu 18.04
Hook testnet - `wss://hooks-testnet.xrpl-labs.com`

**Comment by RichardAH** [comment]
I believe this is fixed. If you could please test on your end? I will also add this to the unit tests shortly.

**Comment by chalith** [comment]
@RichardAH tested. Now the issue is fixed.
