### ISSUE TITLE
Reserve doesn't decrease when a state object is deleted in the hook.

### ISSUE THREAD

**Issue by SavindaSenevirathne** [RichardAH/rippled-hooks#27]
## Issue Description
Account reserve doesn't decrease when a state objected is deleted from the hook. The OwnerCount seems not changing as well.

## Steps to Reproduce
Sample code: [state_delete_reserve.zip](https://github.com/XRPL-Labs/xrpld-hooks/files/7625006/state_delete_reserve.zip)
- Download and extract the given sample code.
- Run run.js file as follows.
`node run.js <hook secret> <rippled server>`
- The script will compile and upload the hook and then invoke hook to create and then remove the object in two transactions.

## Expected Result
Account reserve should decreased by 5 XRP per object deletion.

## Actual Result
Account reserve doesn't change when a state object is deleted.

**Comment by RichardAH** [comment]
Is this still the case?

**Comment by chalith** [comment]
Now this works fine, issue is not there @RichardAH. Can close the issue.
