### ISSUE TITLE
Getting started with docker and hooks dev environment

### ISSUE THREAD

**Issue by Goochie** [RichardAH/rippled-hooks#28]
## Summary

Does any one have any suggestions for setting up dev environment / process. (i am new to docker)

So far i have ...

1. Set up docker
2. Set up test account
3. Deployed example hooks from docker container to my test account - everything is going great ..

Now i have come to the point of wanting to edit some of the .js and hook files - do i have to ...

1. Edit the files of the xrpld-hooks container and then rebuild the container
OR
2. Pull the source from github and makes changes then compile 

I have spent the last day or so looking into both options, i have the Docker plugin for VS code so i can access and edit the internal file and have the github source - just unsure what the best approach.

Any advice would be much appreciated ...

**Comment by WietseWind** [comment]
Please check:

https://dev.to/wietse/hooked-3-tech-preview-release-play-with-smart-contracts-on-the-xrp-ledger-2076

The main repository README, the README per example: https://github.com/XRPL-Labs/xrpld-hooks/tree/hooks-chaining/hook-api-examples

And finally: the docs:

https://xrpl-hooks.readme.io/docs/introduction

https://xrpl-hooks.readme.io/docs/examples

What it comes down to: you run the docker container, edit the files and run the JS inside the container.

If you have specific questions, let us know.

**Comment by Goochie** [comment]
Will do ...
