### ISSUE TITLE
[Notary example fails at propose-txn.js with error] (Version: [1.6.0-hooks])

### ISSUE THREAD

**Issue by treisto** [RichardAH/rippled-hooks#30]
## Issue Description

Notary example fails at propose-txn.js with error.

## Steps to Reproduce

1) Create 5 XRPL accounts: 
- N: notary
- S1: signer 1
- S2: signer 2
- S3: signer 3
- R: receiver of funds proposed in propose_txn.js

2) Install the hook with notary.js on notary account
node notary <N_secret_key, 3, S1_public_key, S2_public_key, S3_public_key>

3) Propose txn:
node propose-txn <S1_secret_key, N_public_key, 100, R_public_key> 

4) Get error while running it:

![image](https://user-images.githubusercontent.com/4274128/138691380-3d02c240-7429-4a7b-9670-ce9c049a11b2.png)

**Comment by RichardAH** [comment]
Thanks for the report. While this most likely is a bug in that file, this is a JS helper, not part of hooks proper and won't be released with hooks amendment. Going to close this.
