### ISSUE TITLE
CentOS EOL broke the docker container

### ISSUE THREAD

**Issue by nitowa** [RichardAH/rippled-hooks#38]
Since the docker container ships with CentOS 8, which had its final EOL date today, it is no longer possible to install programs using `yum`. The issue cannot be addressed without moving the container's base layer to a newer version.

## Issue Description
https://www.centos.org/centos-linux-eol/
https://bugs.centos.org/view.php?id=18394

**Comment by RichardAH** [comment]
We no longer use the docker, it was only v1 hooks.
