### ISSUE TITLE
Emitted transaction fee math error [v1 testnet]

### ISSUE THREAD

**Issue by wojake** [RichardAH/rippled-hooks#40]
Every time my Hook emits a transaction, the emitted transaction's fee is *very* high compared to what I expected.

The fee math seems to be alright, every computation seems to be optimized. The computation used wasn't that extreme, it's just a simple calculation (%).

The code can be found here (carbon off-set hook):
https://gist.github.com/muzam1l/43925143fa19735d8c6505c34d3a6a47

Sample tx:
https://hooks.bithomp.com/explorer/8560723B1CF575E3B491E299091A6C3D404101C37B76BB6F252FBE2E200C847E

Every time my Hook emits a transaction, the fee is always 81.46875 XRP.

I've also seen this happen to another Hook's emitted txs as well (not mine, I was just browsing the network)

**Comment by wojake** [comment]
found the reason why, will post it soon.

**Comment by wojake** [comment]
It seems like the fee is heavily impacted when the etxn_reserve() is called, in which:
1 etxn_reserve will cost the Hook around ~`81.468` XRP

The computation used in my Hook doesn't effect the fee but the transaction itself is, as the more emitted transaction I expect my Hook to execute, the more the fee is:
1 etxn_reserve = `81.46875` XRP ([tx here](https://hooks.bithomp.com/explorer/8560723B1CF575E3B491E299091A6C3D404101C37B76BB6F252FBE2E200C847E))
10 etxn_reserve = `814.6875` XRP ([tx here](https://hooks.bithomp.com/explorer/2CB1A3398880FD53D9A079C5174625B002714ED0562DF7501C98102C6ECF6FE0))
100 etxn_reserve = `8146.56` XRP ([tx here](https://hooks.bithomp.com/explorer/79AE122922B6EC084D74BECEEA9D0DE36742C54C017163C494AF9DF34B54CEF8
))

This is my analysis, I tried my best, I hope this helps my current issue. I think my math fee is in the wrong here.

**Comment by RichardAH** [comment]
This was fixed with v2. Please reopen if you find further issues with fees
