### ISSUE TITLE
Use sort-safe XFL representations

### ISSUE THREAD

**Issue by Mwni** [RichardAH/rippled-hooks#49]
I propose a minor change in the binary representation in order to make XFLs sortable by their casted 64 bit integer value:

bit 62 now is: 0 = negative, 1 = positive
bit 61 - 53: if the XFL is negative, XOR with `0xFFFF`
bit 53 - 0: if the XFL is negative, negate, then XOR with `0x3FFFFFFFFFFFFF`

More about this in the standard's draft:
https://github.com/XRPLF/XRPL-Standards/discussions/39#discussioncomment-2991180

**Comment by RichardAH** [comment]
https://github.com/XRPLF/XRPL-Standards/discussions/39#discussioncomment-4726999
