### ISSUE TITLE
Add "lockedBalance" property to "account_lines" command

### ISSUE THREAD

**Issue by nixer89** [RichardAH/rippled-hooks#50]
When having some IOUs escrowed, the RippleState object contains a "LockedBalances" property.

If I use the "account_lines" command now, it is not visible how many tokens are actually locked in Escrows/Paychans.

A nice feature would be to add a "lockedBalance" property to the account_lines request.

![image](https://user-images.githubusercontent.com/25486793/175008166-75122999-fdfc-4fd9-b229-ca1f6eee202e.png)

**Comment by WietseWind** [comment]
@nixer89 Do you mean this is currently being returned by RPC calls but not displayed by the explorer, or do you mean: to add this to the RPC response?

**Comment by nixer89** [comment]
I meant to add it to the RPC call. When using the "account_objects" method, the RippleState object includes two new properties:

1.: "LockCount"
2.: "LockedBalance"

It would be nice to have the "locked balance" value also returned in the "account_lines" command.
Anyway, the issue is just an reminder for @RichardAH. I was in DM with him already and he is aware of my feature request :-)

**Comment by RichardAH** [comment]
Fixed in https://github.com/XRPL-Labs/xrpld-hooks/commit/73bf8f3fff44be97013670200a2d89e0f2a5760a

**Comment by RichardAH** [comment]
@nixer89 Change is now live on tn2: https://hooks-testnet-v2-explorer.xrpl-labs.com/rM3YFJAHYBufChMHsBLZzwzg7a2oBCP7vV/lines
