### ISSUE TITLE
Bug Report: deleting namespace,  also deletes the hook

### ISSUE THREAD

**Issue by f1f47a23** [RichardAH/rippled-hooks#59]
## Issue Description

while I was on notary.c hook sample, I have detected this possible bug as in the title.

## Steps to Reproduce

in notary sample:

1) set a hook

2) reset namespace

## Expected Result

hooks documentation:
Namespace Reset: ......... If the Corresponding Hook exists, it remains, nothing happens to it.
https://xrpl-hooks.readme.io/docs/sethook-transaction#namespace-reset

## Actual Result

account showing all the hooks transactions
https://hooks-testnet-v2-explorer.xrpl-labs.com/rnLTR74s7sqhdi1p2KiRsdY9VtV7eFzdyD

## Environment

https://hooks-builder.xrpl.org

## Supporting Files

simple notary hook sample files

**Comment by Nanimustshine** [comment]
https://forms.gle/2FJfLTLbdCm1DW6C8

**Comment by Nanimustshine** [comment]
> 
> ## Issue Description
> 
> while I was on notary.c hook sample, I have detected this possible bug as in the title.
> 
> 
> ## Steps to Reproduce
> 
> in notary sample:
> 
> 1) set a hook
> 
> 2) reset namespace
> 
> 
> 
> ## Expected Result
> 
> hooks documentation:
> Namespace Reset: ......... If the Corresponding Hook exists, it remains, nothing happens to it.
> https://xrpl-hooks.readme.io/docs/sethook-transaction#namespace-reset
> 
> 
> ## Actual Result
> 
> account showing all the hooks transactions
> https://hooks-testnet-v2-explorer.xrpl-labs.com/rnLTR74s7sqhdi1p2KiRsdY9VtV7eFzdyD
> 
> ## Environment
> 
> https://hooks-builder.xrpl.org
> 
> ## Supporting Files
> 
> simple notary hook sample files
> 
> 

File a support ticket here
https://forms.gle/2FJfLTLbdCm1DW6C8

**Comment by RichardAH** [comment]
`CreateCode: ""` is the delete hook operation,  it should not be specified.
However I was also able to reproduce your issue when it wasn't specified so this seems like a confirmed bug. I will chase it up in code, thanks!

**Comment by f1f47a23** [comment]
Hi 
Sorry, I had to specify the details better.
That transaction was actually a "delete hook" operation sent by the online hook builder.
Now the real "reset namespace" transaction is lost in the ledger history.
But I just sent a new "reset namespace" transaction and I confirm that indeed the hook was also deleted along with the namespace

https://hooks-testnet-v2-explorer.xrpl-labs.com/tx/4BF5FFA02B1101BC5FEC1C6FAB4B7FC23C692FC2E49457746C0D59760B97B27D

**Comment by RichardAH** [comment]
I'll circle back and ask you to test when this fix is live on v2 testnet, thanks!

**Comment by RichardAH** [comment]
this should be fixed please re-open if not
