### ISSUE TITLE
[STANDALONE TESTING] ICV2-Paychan+Escrow amendment error when creating payment channel.

### ISSUE THREAD

**Issue by dangell7** [RichardAH/rippled-hooks#60]
## Issue Description

Cannot create paychannel for xrp on https://github.com/RichardAH/rippled/tree/PaychanAndEscrowForTokens
Cannot create paychannel for ic on https://github.com/RichardAH/rippled/tree/PaychanAndEscrowForTokens

## Steps to Reproduce

Checkout: https://github.com/Transia-RnD/xrpl.js/tree/denis-icv2

To run the integration tests you need to run the standalone rippled first using docker.

https://github.com/Transia-RnD/xrpl.js/blob/denis-icv2/CONTRIBUTING.md#integration-tests

`npm install && npm run build && npm run test:integration` (Runs the paymentChannelCreate.ts test ONLY)

## Expected Result

Create paychannel for xrp on https://github.com/RichardAH/rippled/tree/PaychanAndEscrowForTokens
Create paychannel for ic on https://github.com/RichardAH/rippled/tree/PaychanAndEscrowForTokens

## Actual Result

create paychannel for xrp: `tecNO_ISSUER`
create paychannel for ic: `temDST_IS_SRC`

## Environment

Rippled Build
https://github.com/Transia-RnD/thehub/releases/tag/icv2-latest

Please keep in mind this is a standalone build for testing so there are lots of places these errors could have been generated from.

**Comment by dangell7** [comment]
Working here: https://github.com/Transia-RnD/rippled/tree/PaychanAndEscrowForTokens

**Comment by Nanimustshine** [comment]
https://forms.gle/2FJfLTLbdCm1DW6C8

**Comment by Nanimustshine** [comment]
> Working here: https://github.com/Transia-RnD/rippled/tree/PaychanAndEscrowForTokens

File a support ticket here
https://forms.gle/2FJfLTLbdCm1DW6C8
